replicaCount: 3
image:
  repository: ermakov880/devops-project
  tag: 5b7272b7601ff75c97c77d20af010706fa95c172
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  nodePort: 30080   # порт, по которому будет доступно приложение
# Ingress отключён – используем NodePort
ingress:
  enabled: false
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  enabled: true
  path: /
  port: 80
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  enabled: true
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 5