apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/K8s
    targetRevision: HEAD
    path: infrastructure/k8s   # или конкретный путь, где лежит storage-class.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default   # для кластерных ресурсов namespace не важен, можно оставить
  syncPolicy:
    automated:
      prune: true
      selfHeal: true