apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: server-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Egorict/K8s.git
    targetRevision: HEAD
    path: infrastructure/k8s/charts/server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true