replicaCount: 3
image:
  repository: ermakov880/devops-project
  tag: dfdc18b02a3b9db59e9a9aa1585c00c9fe764f4c
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  nodePort: 30081   # порт, по которому будет доступно приложение
# Ingress отключён – используем NodePort
ingress:
  enabled: false
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe:
  enabled: true
  path: /
  port: 80
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  enabled: true
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 5