image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

postgresUser: postgres
postgresPassword: postgres
postgresDb: savedata

persistence:
  enabled: true
  size: 1Gi
  # storageClass не нужно указывать, т.к. мы жёстко прописали в PV и PVC
service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

fullnameOverride: "db"