image:
  repository: ermakov880/devops-project-server
  tag: 08440f35e860937a570d1bdb020d2a25a7984909
  pullPolicy: IfNotPresent

service:
  type: NodePort   # было ClusterIP
  port: 8080
  nodePort: 30082  # опционально, можно не указывать — Kubernetes назначит сам

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

replicaCount: 1

env:
  - name: PORT
    value: "8080"
  # Добавьте эти переменные:
  - name: DB_HOST
    value: db-service
  - name: DB_PORT
    value: "5432"
  - name: DB_USER
    value: myuser
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-secret
        key: POSTGRES_PASSWORD
  - name: DB_NAME
    value: mydb