image:
  repository: ermakov880/devops-project-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort   # было ClusterIP
  port: 8080
  nodePort: 30080  # опционально, можно не указывать — Kubernetes назначит сам
  
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

replicaCount: 1

env:
  - name: PORT
    value: "8080"